fga-eps-mds/2019.2-ArBC

docs/mds/Documento_de_arquitetura.md
docs/policies/branches.md
docs/policies/commits.md
docs/policies/issues.md
docs/policies/pull_requests.md

Foram criadas as políticas do repositório
[Documentos de Políticas do Projeto](#18 )
Os documentos de políticas do projeto servem para organização do repositório e de auxílio aos membros mais novos do projeto de como deve ser criado issues, pull requests e etc.
Resolve #18

Políticas do Projeto

---

package-lock.json

Corrigi as vulnerabilidades do repositório.
Correção de vulnerabilidades do projeto.

Correção de vulnerabilidades do repositório.

---

CODE_OF_CONDUCT.md

Adicionar o código de conduta do projeto.
Para que o projeto tenha um código de conduta a ser seguido.
Resolve #33

CÓDIGO DE CONDUTA

---

docs/EAP.md
docs/sprints/Planejamento-Sprint-0.md
docs/sprints/Planejamento-Sprint-1.md
docs/sprints/Planejamento-Sprint-2.md

Adição do documento de Estrutura Analítica do Projeto mostrando os diagramas com classes hierárquicas que formam os pacotes do nosso projeto projeto.
[Elaborar EAP](#37 )
O objetivo de uma EAP é identificar elementos terminais (os produtos, serviços e resultados a serem feitos em um projeto). Assim, a EAP serve como base para a maior parte do planejamento de projeto, trabalhando também com a comunicação da equipe e do cliente.
Ex:
Resolve #37 .

Estrutura Analítica do Projeto (EAP)

---

docs/Termo-Abertura-Projeto.md

Adiciona termo de abertura do projeto.
[Documento de Abetura do Projeto](#7)
Para que o projeto tenha um termo de abertura do projeto.
Resolve #7

Termo de Abertura do Projeto

---

public/index.html
src/App.vue
vue.config.js

Permite a leitura das letras do alfabeto através da câmera de um determinado dispositivo, permitindo que gifs ou imagens possam ser associadas a tais letras.
[US01 - Leitura de Letras](#9)
Para que a leitura de letras seja possível.
Resolve #9

US01 - Leitura de Letras

---

.gitignore
.gitlab-ci.yml
netlify.toml
package.json

Configuração dos ambientes de deploy contínuo.
[Configurar Deploy  Contínuo](#50 )
Para que o aplicativo possua ambientes de implantação de produção e desenvolvimento.
Resolve #50

Configurar deploy contínuo

---

docs/Product-Backlog.md

Criar uma lista priorizada de User Stories que será usada e atualizada ao decorrer do projeto durante as sprints.
[Product Backlog](#6 )
Resolve #6

Backlog de Produto

---

.gitlab-ci.yml

Corrigir os bugs e erros que foram apresentados durante a execução do deploy contínuo.
[Deploy Contínuo](#62)
Para que os o ambiente de deploy possa estar 100% funcional
Resolve #62

Correção de bug do deploy contínuo

---

docs/mds/Documento_de_visao.md

Corrigir erros no documento de visão
[Correções no Documento de Visão](#67 )
Melhorar o documento de visão
Resolve #67

Correções no Documento de Visão

---

docs/Plano-Comunicacao.md

Criar documento referente ao plano de comunicação da disciplina afim de reduzir riscos existentes.
[Plano de Comunicação](#55  )
Resolve #55

Plano de Comunicação

---

docs/Plano-Gerenciamento-Riscos.md

Criar documento referente ao levantamento de Riscos do projeto.
[Documento de Gerenciamento de Riscos](#56    )
Resolve #56

Documento de Gerenciamento de Riscos

---

docs/sprints/Fechamento-Sprint-0.md
docs/sprints/Fechamento-Sprint-1.md
docs/sprints/Fechamento-Sprint-2.md
docs/sprints/Fechamento-Sprint-3.md
docs/sprints/Fechamento-Sprint-4.md
docs/sprints/Planejamento-Sprint-2.md
docs/sprints/Planejamento-Sprint-3.md
docs/sprints/Planejamento-Sprint-4.md

Adição dos resultados de todas as sprints (0 até 4) ao repositório, na Wiki já foram atualizados.

Fechamento das Sprints

---

docs/mds/Documento_de_arquitetura.md

Corrigir erros no documento de arquitetura que apresentava diversas inconsistências
[Refatorar Documento de Arquitetura](#72  )
Para corrigir o documento de arquitetura
**Critérios de Aceitação**
Resolve #72

Refatorar Documento de Arquitetura

---

docs/sprints/Fechamento-Sprint-4.md
docs/sprints/Fechamento-Sprint-5.md
docs/sprints/Planejamento-Sprint-5.md

Criar o documento de Planejamento e Fechamento da Sprint 5 que ocorreu no período de 29/09 até 05/10
[Sprint 5](#76 )
Adição do Planejamento e Fechamento da Sprint 5
**Critérios de Aceitação**
Resolve #76

Planejamento e Fechamento Sprint 5

---

package-lock.json
package.json
src/App.vue
src/services/markersStats.ts
src/services/types.d.ts

Eu, como Educador, desejo que a aplicação possa identificar uma palavra a partir de um conjunto de letras.
[US02 - Identificar Palavra](#10  )
É necessário para que seja possível identificar a palavra lida a partir de vários marcadores e com isso seja possível mostrar o GIF correspondente
**Critérios de Aceitação**
Resolve #10

US02 - Identificar Palavra

---

.env.production
package-lock.json

Adicionar o arquivo de váriaveis de ambiente para o ambiente de produção.
[Adicionar o arquivo de váriaveis de ambiente para o ambiente de produção](#113 )
Para que seja possível fazer requições corretamente no ambiente de produção
Resolve #113

Adicionar arquivo env de produção

---

CONTRIBUTING.md

Adicionar documento de como contribuir na devel.
O documento de como contribuir é de extrema importância para a metodologia Agile, na R1 foi um dos documentos que faltaram. Apesar de já está na wiki ele não foi adicionado ao repositório.

Como Contribuir na devel

---

Postmortem.md

Adicionar documento de post mortem
O documento serve para dizer as lições e recomendações que os membros do grupo obtiveram durante esses últimos 4 meses de estudo e dedicação.

Post Mortem

---

public/manifest.json
src/components/Home.vue
src/router.ts

Muda cor do tema da aplicação econserta URL de início da PWA inexistente
[URL de início da PWA inexistente](#140 )
[Mudar cor do tema da aplicação](#141 )
Para que seja possível acessar a aplicação como PWA e que tenha nossa cor no app
closes #140 
closes #141 
[GIF](https://media.giphy.com/media/ZrUO2YVHIajTi/giphy.gif)

Mudar cor do tema da aplicação e URL de início da PWA inexistente
